updated Routing chapter
cap-react-trainings/presentation pull request #17
Opened 2024-06-25 13:39 UTC by cap-anna

2024-08-02 12:50 UTC, alex-wrede-cap requested changes

2024-08-02 12:50 UTC, alex-wrede-cap commented on src/chapters/06_routing/RoutingChapter.tsx
> +  path="/"
Evtl. hinzufügen, dass es sich hier um createBrowserRouter handelt

2024-08-02 12:50 UTC, alex-wrede-cap commented on src/chapters/06_routing/RoutingChapter.tsx
> +  path="/"
auch ist das formatting irgendwie kaputt (falsche Farben)

2024-08-02 12:50 UTC, alex-wrede-cap commented on src/chapters/06_routing/RoutingChapter.tsx
> +  className={({ isActive, isPending }) =>
evtl. hinzufügen, dass die Elemente isActive, isPending direkt aus dem NavLink destructured werden und die Alternative (kein destructuring) aufzeigen

2024-08-02 12:50 UTC, alex-wrede-cap commented on src/chapters/06_routing/RoutingChapter.tsx
> +        <p>Route</p>
`<p>` sollte lieber `<h3>` sein oder gestyled. Ansonsten fällt das zu wenig auf und es wird schwieriger bei der Suche

2024-08-06 10:11 UTC, cap-anna commented on src/chapters/06_routing/RoutingChapter.tsx
> +  path="/"
ich hab die Variable umgenannt aber an der Verwendung der Stelle steht das auch nochmal dabei. Hab es auch da nochmal hervorgehoben

2024-08-06 10:27 UTC, cap-anna commented on src/chapters/06_routing/RoutingChapter.tsx
> +        <p>Route</p>
passt. hab jetzt allerdings h4 draus gemacht, sah besser aus ;-)

2024-09-24 06:05 UTC, cap-anna commented
@alex-wrede-cap  bitte nochmal prüfen. Kommentare sind eig eingearbeitet ;-)

2024-10-24 10:38 UTC, bejusc commented on src/chapters/06_routing/RoutingChapter.tsx
> +      return fetch("/api/teams/params.teamId");
`return fetch("/api/teams/" + params.teamId);`

2024-10-24 10:41 UTC, bejusc commented on src/chapters/06_routing/RoutingChapter.tsx
> +  path="/"
Sollte man an dieser Stelle vllt auch noch auf die Funktion "createRoutesFromElements" verweisen?
https://reactrouter.com/en/main/utils/create-routes-from-elements#createroutesfromelements

2024-10-31 11:10 UTC, bejusc commented on src/chapters/06_routing/RoutingChapter.tsx
> +  path="/"
Done

2024-10-31 11:11 UTC, merged